import './globals.css'
import { Outfit } from 'next/font/google'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={outfit.className}>

        <header className='flex justify-center py-6 lg:py-7'>
          <div className="w-10/12 lg:w-8/12 flex justify-between">
            <h2 className='text-white text-2xl'>
              Kika Decora
            </h2>
            <div className='border rounded-full text-green-700 border-green-700 text-xl'>
              WA
            </div>
          </div>
        </header>

        {children}
        
      </body>
    </html>
  )
}
